--------------------------------------------------------
--  Ref Constraints for Table MEDIDA_DISCIPLINAR
--------------------------------------------------------

  ALTER TABLE "MEDIDA_DISCIPLINAR" ADD CONSTRAINT "MEDIDA_DISCIPLINAR_FK_PESSOA" FOREIGN KEY ("FK_PESSOA")
	  REFERENCES "PESSOA" ("ID_NUM_CPF") ENABLE;
  ALTER TABLE "MEDIDA_DISCIPLINAR" ADD CONSTRAINT "MEDIDA_DISCIPLINAR_FK_TIPO_MEDIDA" FOREIGN KEY ("FK_ID_COD_MEDIDA")
	  REFERENCES "TIPO_MEDIDA" ("ID_MEDIDA") ENABLE;
