--------------------------------------------------------
--  Ref Constraints for Table PESSOA
--------------------------------------------------------

  ALTER TABLE "PESSOA" ADD CONSTRAINT "PESSOA_FK_TIME" FOREIGN KEY ("FK_TIME")
	  REFERENCES "TIME" ("ID_TIME") ENABLE;
  ALTER TABLE "PESSOA" ADD CONSTRAINT "PESSOA_FK_CIDADE" FOREIGN KEY ("FK_CIDADE")
	  REFERENCES "CIDADE" ("ID_CIDADE") ENABLE;
  ALTER TABLE "PESSOA" ADD CONSTRAINT "PESSOA_FK_ESTADO" FOREIGN KEY ("FK_ESTADO")
	  REFERENCES "ESTADO" ("ID_ESTADO") ENABLE;
  ALTER TABLE "PESSOA" ADD CONSTRAINT "PESSOA_FK_PAIS" FOREIGN KEY ("FK_PAIS")
	  REFERENCES "PAIS" ("ID_PAIS") ENABLE;
